edit_current_event_message = (
    "<b>Welcome to Bookly!</b>\n\n"
    "<b>Let's work on the current event. 🎯</b>\n\n"
    "This menu allows you to edit the current event. Here you can easily:\n\n"
    "1. <b>View and edit coaches:</b>\n"
    "\t • View coach's schedule\n"
    "\t • Edit info about coach\n"
    "2. <b>Search a dancer</b>:\n"
    "\t • Find a dancer and view their bookings\n"
    "3. <b>View full schedule:</b>\n"
    "\t • View the schedule in Excel sheets with payment mark\n\n"
    "4. <b>Camp settings<b/>"
    "\t • Edit info about coaches\n"
    "\t • Add new coach\n"
    "\t • edit information about camp\n"
    "<b>What would you like to do? </b>👇"
)
