edit_current_event_message = ("Let's work on the current event. 🎯\n\n"
                              "This menu allows you to edit the current event. Here you can easily:\n\n"
                              "1. Coach:\n"
                              "\t • Add coaches\n"
                              "\t • Edit coaches\n\n"
                              "2. Camp info:\n"
                              "\t • Add additional info about the camp like the location, date, etc.\n"
                              "\t • View the Schedule in Excel sheets with payment mark\n\n"
                              "3. Dancers info:\n"
                              "\t • Search for a specific dancer and view their paid and unpaid bookings\n"
                              "\t • Mark payments to control finances\n\n"
                              "What would you like to do? 👇")
