var = {'Marek Kosaty': array(['Not Available  & Not Available ',
                              'Vitalii Grygorovych & Rakytska Daria',
                              'Artem Hryschenko & Vitalina Kolba',
                              ' Nikita Kholyavko & Ulyana Shmalenyuk',
                              'Shvurlo Melnuchyk & Mariana Bryk',
                              'Shvurlo Melnuchyk & Mariana Bryk', 'Beley Anna & Mariana Bryk',
                              'Beley Anna & Mariana Bryk', 'Bogdan Julia  & Tetiana Balla',
                              'Alina Grechkosij & Alina Grechkosij', nan, nan], dtype=object),
       'Marek Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Valerio Colantoni': array([nan, 'Artem Hryschenko & Vitalina Kolba',
                                   'Bogdan Julia  & Tetiana Balla', 'Sazanov  & Karolina Rybak',
                                   'Anton Mariya & Mullyar Olexandr',
                                   'Shmyrov Serhii & Kateryna Voronaya',
                                   'Mark Solomia  & Mullyar Olexandr',
                                   'Ivanyk Ivan & Valeria Derkach'], dtype=object),
       'Valerio Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Stephen Hannah': array([nan, nan, nan, nan, 'Shmyrov Serhii & Kateryna Voronaya', nan,
                                'Kateryna Petrushevska & Kateryna Petrushevska', nan], dtype=object),
       'Stephen Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Sergiu Rusu': array([nan, nan, nan, nan, nan, nan,
                             'Ivan Cherniavskyi  & Ivan Cherniavskyi ',
                             'Vladislava Vladabarbie  & Vladislava Vladabarbie '], dtype=object),
       'Sergiu Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Mirko Gozzoli': array([nan, 'Shmyrov Serhii & Kateryna Voronaya',
                               'Mullyar Olexandr & Mullyar Olexandr', 'Star Dance & Star Dance',
                               'Alina Grechkosij & Alina Grechkosij',
                               'Nazar Mira  & Tetiana Balla',
                               'Ryabuha Oleksandra & Andrii Zinchenko',
                               'Ryabuha Oleksandra & Andrii Zinchenko'], dtype=object),
       'Mirko Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Jurij Batagelj': array([nan, nan, nan, nan, nan, nan, 'Olena Boiko & Yevhenii Borushko',
                                'Ladanovskiy Andriy Sidorova Mariya & Star Dance'], dtype=object),
       'Jurij Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Alex Ivanets': array([nan, nan, nan, 'Anastasiia Moroz & Olexandr Moroz',
                              'Ivan Katya & Star Dance',
                              'Klimenko Nazar Syan Angelina & Star Dance',
                              'Anastasiia Moroz & Olexandr Moroz',
                              'Lisenko Mark Chernoivanenko Yuliya & Star Dance'], dtype=object),
       'Alex Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Arunas Bizokas': array(['Kateryna Petrushevska & Kateryna Petrushevska',
                                'Davyd Komarnytskiy & Angelina Cherkovska',
                                'Roman Anastasia  & Mullyar Olexandr',
                                'Ladanovskiy Andriy Sidorova Mariya & Star Dance',
                                'Dmytro Yevtyeryev & Dmytro Yevtyeryev',
                                'Lisenko Mark Chernoivanenko Yuliya & Star Dance',
                                'Anna Kapshuchenko & Nazar Honcharenko',
                                'Oleksandr Rozumei  & Dariya Muryzina'], dtype=object),
       'Arunas Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Lika Dikaya': array([nan, nan, nan, nan, nan, nan, nan, nan], dtype=object),
       'Lika Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Igor Reznik': array([nan, nan, nan, nan,
                                                                                              'Zayets Lukian Gavrulyk Annaliza  & Mariana Bryk',
                                                                                              'Zayets Lukian Gavrulyk Annaliza  & Mariana Bryk',
                                                                                              nan, nan],
                                                                                             dtype=object),
       'Igor Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Yuliya Sadovskaya': array([nan, nan, nan, ' Nikita Kholyavko & Ulyana Shmalenyuk', nan, nan,
                                   nan, 'Alina Grechkosij & Alina Grechkosij'], dtype=object),
       'Yuliya Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Denys Fedorov': array([nan, nan, nan, nan, nan, nan, nan, nan], dtype=object),
       'Denys Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Oleksii Balla': array([nan, nan, nan, nan, nan, nan, nan, nan], dtype=object),
       'Oleksii Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Annette Sudol': array([nan, nan, nan, nan, nan, 'Vitaliy Erfan & Viktoriya Zaprudska',
                               'Shmyrov Serhii & Kateryna Voronaya',
                               'Ulyana Benkivska & Oleksiy Kuvichynskyi '], dtype=object),
       'Annette Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Simone Segatori': array([nan, nan, nan, nan, 'Ulyana Benkivska & Oleksiy Kuvichynskyi ',
                                 'Dmytro Yevtyeryev & Dmytro Yevtyeryev', nan, nan], dtype=object),
       'Simone Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Ruslan Shevchenko': array([nan, nan, nan, nan, nan, nan, nan, nan], dtype=object),
       'Ruslan Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Denys Korostashov': array([nan, nan, nan, nan, nan, nan, nan, nan], dtype=object),
       'Natalie Kostyleva': array([nan, nan, nan, nan, nan, nan, nan, nan], dtype=object),
       'Natalie Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Andrii Zinchenko': array([nan, nan, nan, nan, nan, nan, nan, nan], dtype=object),
       'Andrii Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Viktoria Kharchenko': array([nan, nan, nan, 'Kokiza Andrij & Vergazova Rinata',
                                     'Arina Samoilenko & Arina Samoilenko',
                                     'Roman Olesya & Mullyar Olexandr',
                                     'Roman Olesya & Mullyar Olexandr',
                                     'Davyd Komarnytskiy & Angelina Cherkovska'], dtype=object),
       'Viktoria Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Olga Urumova': array([nan, nan, 'Ryabuha Oleksandra & Andrii Zinchenko',
                              'Arina Samoilenko & Arina Samoilenko',
                              'Ryabuha Oleksandra & Andrii Zinchenko',
                              'Ryabuha Oleksandra & Andrii Zinchenko', nan, nan], dtype=object),
       'Olga Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Olexandr Gaydash': array([nan, nan, nan, nan, nan, nan, 'Beley Anna & Mariana Bryk',
                                  'Beley Anna & Mariana Bryk'], dtype=object),
       'Olexandr Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Kate Sakhanenko': array([nan, nan, nan, nan, nan, nan, nan,
                                 'Zayets Lukian Gavrulyk Annaliza  & Mariana Bryk'], dtype=object),
       'Kate Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Yuri Kosovych': array([nan, nan, nan, nan, nan, nan, nan, nan], dtype=object),
       'Yuri Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Tetiana Balla': array([nan, nan, nan, nan, nan, nan, nan, nan], dtype=object),
       'Tetiana Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Denys Ryeka': array([nan, nan, nan, nan, nan, nan, nan, nan], dtype=object),
       'Igor Yaremenko': array([nan, nan, nan, nan, 'Boyko Tarahan  & Mariana Bryk',
                                'Boyko Tarahan  & Mariana Bryk', nan,
                                'Zayets Maksym Blazevsjka Karolina  & Mariana Bryk'], dtype=object),
       'Kateryna Krut': array([nan, nan, nan, nan, nan, nan, nan, nan], dtype=object),
       'Kateryna Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Evgeniy Kvitka': array([nan, nan, nan, nan, nan, nan, nan, nan], dtype=object),
       'Evgeniy Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Yaroslav Galay': array([nan, nan, nan, nan, nan, nan, nan, nan], dtype=object),
       'Yaroslav Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Mariia Yur': array([nan, nan, nan, nan, nan, nan, nan, nan], dtype=object),
       'Mariia Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Dora Kilin': array([nan, nan, nan, 'Shmyrov Serhii & Kateryna Voronaya',
                            'Vitaliy Erfan & Viktoriya Zaprudska',
                            'Bogdan Julia  & Tetiana Balla',
                            'Timofey Chernenko & Timofey Chernenko', nan], dtype=object),
       'Dora Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Masha Savchuk': array([nan, 'Beley Anna & Mariana Bryk', 'Beley Anna & Mariana Bryk',
                               'Beley Anna & Mariana Bryk', 'Beley Anna & Mariana Bryk',
                               ' Boitsova Polina & Tykhyi Bogdan',
                               ' Boitsova Polina & Tykhyi Bogdan',
                               'Vitaliy Erfan & Viktoriya Zaprudska'], dtype=object),
       'Masha Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Marko Sirocchi': array([nan, nan, nan, nan, nan,
                                'Kateryna Petrushevska & Kateryna Petrushevska', nan,
                                'Shmyrov Serhii & Kateryna Voronaya'], dtype=object),
       'Marko Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'],
       'Olexandr Bezkrovniy': array([nan, ' Nikita Kholyavko & Ulyana Shmalenyuk',
                                     ' Boitsova Polina & Tykhyi Bogdan',
                                     ' Boitsova Polina & Tykhyi Bogdan',
                                     'Oliunyk Bohaychuk  & Mariana Bryk',
                                     'Oliunyk Bohaychuk  & Mariana Bryk',
                                     'Striletsky Roma Bulvarenko Violetta & Mariana Bryk',
                                     'Striletsky Roma Bulvarenko Violetta & Mariana Bryk'], dtype=object)}
df_dict {'Marek Kosaty': array(['Not Available  & Not Available ',
       'Vitalii Grygorovych & Rakytska Daria',
       'Artem Hryschenko & Vitalina Kolba',
       ' Nikita Kholyavko & Ulyana Shmalenyuk',
       'Shvurlo Melnuchyk & Mariana Bryk',
       'Shvurlo Melnuchyk & Mariana Bryk', 'Beley Anna & Mariana Bryk',
       'Beley Anna & Mariana Bryk', 'Bogdan Julia  & Tetiana Balla',
       'Alina Grechkosij & Alina Grechkosij', nan, nan], dtype=object), 'Marek Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Valerio Colantoni': array([nan, 'Artem Hryschenko & Vitalina Kolba',
       'Bogdan Julia  & Tetiana Balla', 'Sazanov  & Karolina Rybak',
       'Anton Mariya & Mullyar Olexandr',
       'Shmyrov Serhii & Kateryna Voronaya',
       'Mark Solomia  & Mullyar Olexandr',
       'Ivanyk Ivan & Valeria Derkach'], dtype=object), 'Valerio Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Stephen Hannah': array([nan, nan, nan, nan, 'Shmyrov Serhii & Kateryna Voronaya', nan,
       'Kateryna Petrushevska & Kateryna Petrushevska', nan], dtype=object), 'Stephen Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Sergiu Rusu': array([nan, nan, nan, nan, nan, nan,
       'Ivan Cherniavskyi  & Ivan Cherniavskyi ',
       'Vladislava Vladabarbie  & Vladislava Vladabarbie '], dtype=object), 'Sergiu Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Mirko Gozzoli': array([nan, 'Shmyrov Serhii & Kateryna Voronaya',
       'Mullyar Olexandr & Mullyar Olexandr', 'Star Dance & Star Dance',
       'Alina Grechkosij & Alina Grechkosij',
       'Nazar Mira  & Tetiana Balla',
       'Ryabuha Oleksandra & Andrii Zinchenko',
       'Ryabuha Oleksandra & Andrii Zinchenko'], dtype=object), 'Mirko Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Jurij Batagelj': array([nan, nan, nan, nan, nan, nan, 'Olena Boiko & Yevhenii Borushko',
       'Ladanovskiy Andriy Sidorova Mariya & Star Dance'], dtype=object), 'Jurij Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Alex Ivanets': array([nan, nan, nan, 'Anastasiia Moroz & Olexandr Moroz',
       'Ivan Katya & Star Dance',
       'Klimenko Nazar Syan Angelina & Star Dance',
       'Anastasiia Moroz & Olexandr Moroz',
       'Lisenko Mark Chernoivanenko Yuliya & Star Dance'], dtype=object), 'Alex Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Arunas Bizokas': array([nan, 'Vasyliuk Ivan & Sofia Kaletynska',
       'Timofey Chernenko & Timofey Chernenko',
       'Timofey Chernenko & Timofey Chernenko',
       'Timofey Chernenko & Timofey Chernenko',
       'Vladislava Vladabarbie  & Vladislava Vladabarbie ',
       'Vitaliy Erfan & Viktoriya Zaprudska',
       'Ryabuha Oleksandra & Andrii Zinchenko',
       'Ivanyk Ivan & Valeria Derkach', 'Nazar Mira  & Tetiana Balla',
       'Not Available  & Not Available ',
       'Ihor Sofia  & Mullyar Olexandr'], dtype=object), 'Arunas Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Lika Dikaya': array([nan, nan, nan, nan, nan, nan, nan, nan], dtype=object), 'Lika Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Igor Reznik': array([nan, nan, nan, nan,
       'Zayets Lukian Gavrulyk Annaliza  & Mariana Bryk',
       'Zayets Lukian Gavrulyk Annaliza  & Mariana Bryk', nan, nan],
      dtype=object), 'Igor Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Yuliya Sadovskaya': array([nan, nan, nan, ' Nikita Kholyavko & Ulyana Shmalenyuk', nan, nan,
       nan, 'Alina Grechkosij & Alina Grechkosij'], dtype=object), 'Yuliya Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Denys Fedorov': array([nan, nan, nan, nan, nan, nan, nan, nan], dtype=object), 'Denys Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Oleksii Balla': array([nan, nan, nan, nan, nan, nan, nan, nan], dtype=object), 'Oleksii Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Annette Sudol': array([nan, nan, nan, nan, nan, 'Vitaliy Erfan & Viktoriya Zaprudska',
       'Shmyrov Serhii & Kateryna Voronaya',
       'Ulyana Benkivska & Oleksiy Kuvichynskyi '], dtype=object), 'Annette Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Simone Segatori': array([nan, nan, nan, nan, 'Ulyana Benkivska & Oleksiy Kuvichynskyi ',
       'Dmytro Yevtyeryev & Dmytro Yevtyeryev', nan, nan], dtype=object), 'Simone Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Ruslan Shevchenko': array([nan, nan, nan, nan, nan, nan, nan, nan], dtype=object), 'Ruslan Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Denys Korostashov': array([nan, nan, nan, nan, nan, nan, nan, nan], dtype=object), 'Natalie Kostyleva': array([nan, nan, nan, nan, nan, nan, nan, nan], dtype=object), 'Natalie Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Andrii Zinchenko': array([nan, nan, nan, nan, nan, nan, nan, nan], dtype=object), 'Andrii Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Viktoria Kharchenko': array([nan, nan, nan, 'Kokiza Andrij & Vergazova Rinata',
       'Arina Samoilenko & Arina Samoilenko',
       'Roman Olesya & Mullyar Olexandr',
       'Roman Olesya & Mullyar Olexandr',
       'Davyd Komarnytskiy & Angelina Cherkovska'], dtype=object), 'Viktoria Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Olga Urumova': array([nan, nan, 'Ryabuha Oleksandra & Andrii Zinchenko',
       'Arina Samoilenko & Arina Samoilenko',
       'Ryabuha Oleksandra & Andrii Zinchenko',
       'Ryabuha Oleksandra & Andrii Zinchenko', nan, nan], dtype=object), 'Olga Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Olexandr Gaydash': array([nan, nan, nan, nan, nan, nan, 'Beley Anna & Mariana Bryk',
       'Beley Anna & Mariana Bryk'], dtype=object), 'Olexandr Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Kate Sakhanenko': array([nan, nan, nan, nan, nan, nan, nan,
       'Zayets Lukian Gavrulyk Annaliza  & Mariana Bryk'], dtype=object), 'Kate Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Yuri Kosovych': array([nan, nan, nan, nan, nan, nan, nan, nan], dtype=object), 'Yuri Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Tetiana Balla': array([nan, nan, nan, nan, nan, nan, nan, nan], dtype=object), 'Tetiana Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Denys Ryeka': array([nan, nan, nan, nan, nan, nan, nan, nan], dtype=object), 'Igor Yaremenko': array([nan, nan, nan, nan, 'Boyko Tarahan  & Mariana Bryk',
       'Boyko Tarahan  & Mariana Bryk', nan,
       'Zayets Maksym Blazevsjka Karolina  & Mariana Bryk'], dtype=object), 'Kateryna Krut': array([nan, nan, nan, nan, nan, nan, nan, nan], dtype=object), 'Kateryna Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Evgeniy Kvitka': array([nan, nan, nan, nan, nan, nan, nan, nan], dtype=object), 'Evgeniy Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Yaroslav Galay': array([nan, nan, nan, nan, nan, nan, nan, nan], dtype=object), 'Yaroslav Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Mariia Yur': array([nan, nan, nan, nan, nan, nan, nan, nan], dtype=object), 'Mariia Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Dora Kilin': array([nan, nan, nan, 'Shmyrov Serhii & Kateryna Voronaya',
       'Vitaliy Erfan & Viktoriya Zaprudska',
       'Bogdan Julia  & Tetiana Balla',
       'Timofey Chernenko & Timofey Chernenko', nan], dtype=object), 'Dora Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Masha Savchuk': array([nan, 'Beley Anna & Mariana Bryk', 'Beley Anna & Mariana Bryk',
       'Beley Anna & Mariana Bryk', 'Beley Anna & Mariana Bryk',
       ' Boitsova Polina & Tykhyi Bogdan',
       ' Boitsova Polina & Tykhyi Bogdan',
       'Vitaliy Erfan & Viktoriya Zaprudska'], dtype=object), 'Masha Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Marko Sirocchi': array([nan, nan, nan, nan, nan,
       'Kateryna Petrushevska & Kateryna Petrushevska', nan,
       'Shmyrov Serhii & Kateryna Voronaya'], dtype=object), 'Marko Payment Status': ['❌', '❌', '❌', '❌', '❌', '❌', '❌', '❌'], 'Olexandr Bezkrovniy': array([nan, ' Nikita Kholyavko & Ulyana Shmalenyuk',
       ' Boitsova Polina & Tykhyi Bogdan',
       ' Boitsova Polina & Tykhyi Bogdan',
       'Oliunyk Bohaychuk  & Mariana Bryk',
       'Oliunyk Bohaychuk  & Mariana Bryk',
       'Striletsky Roma Bulvarenko Violetta & Mariana Bryk',
       'Striletsky Roma Bulvarenko Violetta & Mariana Bryk'], dtype=object)}
